language: python
cache: pip

python:
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - git fetch --unshallow || true

install:
  - pip install -U pip setuptools
  - pip install --pre pybuilder
  - pyb -X install_dependencies

script:
  - pyb -X

deploy:
  provider: pypi
  user: twentybn-machine-user
  server: https://upload.pypi.org/legacy/
  distributions: sdist
  skip_cleanup: true
  password:
    secure: "WT3stSIXupOOnbcmIo4aHkfhrq07KYa4pGmGBkthsPGFQnaHL8v25G9IUi4hQmG/PkpwmhMY0YLB4EwudTn0v8GD5s/CxlDbEgIKe5qB+NNPEP/1fMnjV96TU10IoRa6gWuA8xlMx2VuHjn6TI1plbuFkwN+LUwXU4sqw+imuhKIMk7QYl8a8VVmCCQM3e/KQIpKeQSQEtyQYgfAf/ZETWomWnIS7+gAUK3pqYVLJXu4T6+8tUcv/JvvrqkLAiE156VbxY1T4ZplllzInVB+DuxjCD1bHone3I2IYWIlAbwSYxIuX1JDO/VT8PM4IV8fQvZDcJe2s0udk1b/KoVeK1GOc3r3mUkvKu5jHSVWYNYpwCgRuCvAax7GXpAeIHfVQ0mpwMWh8/OUEVWj820JU2CnBjRTs1NxtKrsZ7uRxpjY7YLCs7Jo9X/RPIKo/iUJvgRAtofGAjPhss3UH/xPrxAYzldudr2dhb+F7MrLICQNJpbYN5zSfRyJXJ2XMJJ2mrqaYw1A62QUn/9c7i9B9X1nNRjWpvzJdMIqlNN4k713LulC9lO9oP/6EjDS5M0cgJLFK+V8uYRebhV6AreSdZqDND0hS4UgowUpNNMbJcKlS9KzJ23Jbg/Q7QXe2X2P9RskjK4/r+afDDOzzeJ+ycJZkX/e13s92xklhNmJ+uQ="
  on:
    repo: TwentyBN/twentybn-dl
    python: '3.6'
    branch: master
