language: python
cache: pip

python:
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - git fetch --unshallow || true

install:
  - pip install -U pip setuptools
  - pip install --pre pybuilder
  - pyb -X install_dependencies

script:
  - pyb -X

deploy:
  provider: pypi
  user: twentybn-machine-user
  server: https://upload.pypi.org/legacy/
  distributions: sdist
  skip_cleanup: true
  password:
    secure: "gyY0QnW2nrT/qHYLd0V1z+wGZmnfcEuQ7NpIuFvj7N+sBDJX0waLh8frTrPt5A6CL5uoMpeHFyqMbvgjl7f12e8XxlaS5+gVSISd8IV261JYLNSE1jupr5kkeg1OrVZXkeP8zx4t3GD2yXPq1xLl745gqiWG+klF1YpZ1UQRPSZ+H7/6OQgBK5oDWN6N05JvfnKTYm6TC0sVz4hzV0vAzkxJ8PQHiYf5dmI8QeYx8PHU5M+6Cf0NVugKOzfH/265ymgDf0I2DpFn5Ju0Rzfv9n4i7l5WmAA6TdrkIs9axLDCNCfJ5JQSkqO0+jTWKt0SCLQipMu83lIBxGOVRBCSM5jhpO0yjt7so652+WbpTRhWrhxXNacFAT+wvhp4tU2qRd/J6lkyJ1EHeZ1TVo/AkdJEdoePSBlCRLMXja+WR4MgOm/yllje3EkTKpo+fJR7sVcPqzcrAeCpy8lBVRjgBpdFEtqvZ5VyMCGo3c9X/lvFL3a1IeJw/5dsZx9kQ8MFRCOX/+Y5aOCbDnDdZVEb6Ohg4NQjb46vAKHL86GEn+fsnDR+dwcOU7r97yiQ7J7nnDZE9sP9mi5aCW4R0ht2Cio/s+j7Opk8KKiAQAo1/eoIMkbgW8dBMlTpuEo5QKbfccx1XDlee4EEzK2JZEsTkz2CzswGdg0T68iKb4hlHw0="
  on:
    repo: TwentyBN/twentybn-dl
    python: '3.6'
    branch: master
