language: python
cache: pip

python:
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - git fetch --unshallow || true

install:
  - pip install -U pip setuptools
  - pip install --pre pybuilder
  - pyb -X install_dependencies

script:
  - pyb -X

deploy:
  provider: pypi
  user: twentybn-machine-user
  server: https://upload.pypi.org/legacy/
  distributions: sdist
  skip_cleanup: true
  password:
    secure: "fMSTKXLbqhP40fwk3SQVP4UWKJsOM8tjLE/4nFyLcXaAQLnOrhH+kAS5nqnSIV3GGlCiqP0dOUNve3a3wHSKX1MGDPzrWOWTExWziEFCfaDV8kDJ3+TpNrDcBkyf34NIpo8NlZjAlDoiTDLLycKvbJlvgq/AjSb7ViXN0bpmw/VMKSijJeCHkFNGFcQjlFf47xO4dRShlQRvM5/AX+5X+8YvbxJR/RSJUKyfj1EJXO3Vri0JH6izG81rujMexWKOk4aUYgB7J5NxNpiMmaJv3heRz3baamInSUM9HIuzy6gSF/3F0WHldFhtBnKyEZ4/DhBpP4Us6wWTipfjQie/0TDgTcSeZO8pecO3OOiozVYB691O3jYjsQ4ay2eer26li5YjsVgdCpNmckWDs+9utJU3szPKJWAsN73QZmfmwbOo175FmdIQ7L1yapvtRpXUHGnqL9bqXeRKNQ/smlcR/6szVzoHEoytynFfVgMiFGCt8hU3xPbH3/DWvtkHfjhLIWEytLXhDaepC1w37ukx4MNMcovy2aPB5lKSc6SAIGbuJfr6tKGwmJ/Jj7bkt82mG3oTClA9WvzbICsIpIdZulP3G6y4pW4M32J8bhKupoBAqV6+bFQnU80IjpuuD/kcveu/+W9jp4H+BjJEPvFNREhNTvlg/TCSXHIidRuZmlI="
  on:
    repo: TwentyBN/twentybn-dl
    python: '3.6'
    branch: master
