#!/usr/bin/env python
import os
import os.path as op
import itertools


HTTP_ENDPOINT_BASE = "https://s3-eu-west-1.amazonaws.com/20bn-public-datasets/"
DOWNLOAD_TARGET_BASE = op.expandvars('$HOME/20bn-datasets')
LOWERCASE_ALPHABET = ''.join([chr(i) for i in range(97, 123)])


class Dataset(object):
    """ Dataset on S3 accessible via HTTP. """

    def __init__(self, name, version, last):
        self.name = name
        self.version = version
        self.last = last
        self.tmp_dir = op.join(DOWNLOAD_TARGET_BASE, self.name, 'tmp')
        self.init_files()
        self.ensure_directories_exist()

    def init_files(self):
        self.files = [self.filename(s)
                      for s in suffix_generator(self.last)]

    def filename(self, suffix):
        return "20bn-{}-{}-{}".format(self.name, self.version, suffix)

    def ensure_directories_exist(self):
        os.makedirs(self.tmp_dir, exist_ok=True)

    def urls(self):
        pass

    def download_chunks(self):
        pass


def suffix_generator(last):
    """ Generate filename suffixes.

    Will genrate combination of two letter suffixes, starting at 'aa' and
    finishing at last.

    """
    char_pairs = [''.join(i) for i in
                  itertools.combinations(LOWERCASE_ALPHABET, 2)]
    return list(itertools.takewhile(lambda x: x <= last, char_pairs))


SomethingSomething = Dataset('something-something', 'v1', 'be')
Jester = Dataset('jester', 'v1', 'au')


if __name__ == '__main__':
    print("Will download to: '{}'".format(DOWNLOAD_TARGET_BASE))
    os.makedirs(DOWNLOAD_TARGET_BASE, exist_ok=True)
