#!/usr/bin/env python

from twentybn_dl.main import SomethingSomething

if __name__ == '__main__':
    #print("Will download to: '{}'".format(DOWNLOAD_TARGET_BASE))
    #os.makedirs(DOWNLOAD_TARGET_BASE, exist_ok=True)
    #SomethingSomething.download_chunks()
    #SomethingSomething.ensure_chunks_exist()
    #SomethingSomething.concat_chunks()
    #SomethingSomething.ensure_chunk_md5sums_match()
    SomethingSomething.ensure_bigtgz_md5sum_match()

